time window:
  begin: "2018-04-14T21:00:00Z"
  end: "2023-12-15T03:00:00Z"

observations:
- obs space:
    name: "satwind_ahi-h8"
    observed variables: [windSpeed, windDirection]
    derived variables: [windEastward, windNorthward]
    simulated variables: [windEastward, windNorthward]
    obsdatain:
      engine:
        type: script 
        script file: "bufr2ioda_satwnd_amv_ahi.py"
        args:
          input_path: "./testinput/2021080100/gdas.t00z.satwnd.tm00.bufr_d"
          mapping_path: "./bufr2ioda_satwnd_amv_ahi_mapping.yaml"
          category: "h8"
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/script_backend/gdas.t00z.satwnd.ahi_h8.tm00.nc"

- obs space:
    name: "satwind_ahi-h9"
    observed variables: [windSpeed, windDirection]
    derived variables: [windEastward, windNorthward]
    simulated variables: [windEastward, windNorthward]
    obsdatain:
      engine:
        type: script 
        script file: "bufr2ioda_satwnd_amv_ahi.py"
        args:
          input_path: "./testinput/2021080100/gdas.t00z.satwnd.tm00.bufr_d"
          mapping_path: "./bufr2ioda_satwnd_amv_ahi_mapping.yaml"
          category: "h9"
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/script_backend/gdas.t00z.satwnd.ahi_h9.tm00.nc"
