time window:
  begin: "2018-04-14T21:00:00Z"
  end: "2023-12-15T03:00:00Z"

observations:
- obs space:
    name: "satwind_viirs-npp"
    simulated variables: [windDirection, windSpeed]
    obsdatain:
      engine:
        type: bufr 
        obsfile: "./testinput/2021080100/gdas.t00z.satwnd.tm00.bufr_d"
        mapping file: "./bufr2ioda_satwnd_amv_viirs_mapping.yaml"
        category: ["npp"]
        cache categories:            # optional
          - ["npp"]
          - ["n20"]
          - ["n21"]
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/bufr_backend/gdas.t00z.satwnd.viirs_npp.tm00.nc"

- obs space:
    name: "satwind_viirs-n20"
    simulated variables: [windDirection, windSpeed]
    obsdatain:
      engine:
        type: bufr
        obsfile: "./testinput/2021080100/gdas.t00z.satwnd.tm00.bufr_d"
        mapping file: "./bufr2ioda_satwnd_amv_viirs_mapping.yaml"
        category: ["n20"]
        cache categories:            # optional
          - ["npp"]
          - ["n20"]
          - ["n21"]
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/bufr_backend/gdas.t00z.satwnd.viirs_n20.tm00.nc"

- obs space:
    name: "satwind_viirs-n21"
    simulated variables: [windDirection, windSpeed]
    obsdatain:
      engine:
        type: bufr
        obsfile: "./testinput/2021080100/gdas.t00z.satwnd.tm00.bufr_d"
        mapping file: "./bufr2ioda_satwnd_amv_viirs_mapping.yaml"
        category: ["n21"]
        cache categories:            # optional
          - ["npp"]
          - ["n20"]
          - ["n21"]
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/bufr_backend/gdas.t00z.satwnd.viirs_n21.tm00.nc"
