time window:
  begin: "2021-07-31T21:00:00Z"
  end: "2021-08-01T03:00:00Z"
  bound to include: begin

observations:
- obs space:
    name: "AIRCFT"
    simulated variables: ['airTemperature','specificHumidity','windNorthward','windEastward']
    obsdatain:
      engine:
        type: bufr
        obsfile: "./testinput/2021080100/gdas.t00z.acft_profiles.tm00.prepbufr"
        mapping file: "./bufr_acft_profiles_prepbufr_mapping.yaml"
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/bufr4backend/gdas.t00z.acft_profiles_prepbufr.tm00_mpi0.nc"
