time window:
  begin: "2021-07-31T21:00:00Z"
  end: "2021-08-01T03:00:00Z"
  bound to include: begin

observations:
- obs space:
    name: "ADPSFC"
    observed variables: ['stationElevation','stationPressure']
    derived variables: ['stationElevation','stationPressure']
    simulated variables: ['stationElevation','stationPressure']
    obsdatain:
      engine:
        type: script
        script file: "bufr_adpsfc_prepbufr.py"
        args:
          input_path: "testinput/2021080100/gdas.t00z.adpsfc.tm00.prepbufr"
          mapping_path: "./bufr_adpsfc_prepbufr_mapping.yaml"
          cycle_time: "2021080100"
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/script4backend/gdas.t00z.adpsfc_prepbufr.tm00_mpi4.nc"
