time window:
  begin: "2018-04-14T21:00:00Z"
  end: "2023-12-15T03:00:00Z"

observations:
- obs space:
    name: "satwind_goes-16"
    observed variables: [windSpeed, windDirection]
    derived variables: [windEastward, windNorthward]
    simulated variables: [windEastward, windNorthward]
    obsdatain:
      engine:
        type: script 
        script file: "bufr2ioda_satwnd_amv_goes.py"
        args:
          input_path: "./testinput/gdas.t00z.satwnd.tm00.bufr_d"
          mapping_path: "./bufr2ioda_satwnd_amv_goes_mapping.yaml"
          category: "goes-16"
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/script_backend/gdas.t00z.satwnd.abi_goes-16.tm00.nc"

- obs space:
    name: "satwind_goes-17"
    observed variables: [windSpeed, windDirection]
    derived variables: [windEastward, windNorthward]
    simulated variables: [windEastward, windNorthward]
    obsdatain:
      engine:
        type: script 
        script file: "bufr2ioda_satwnd_amv_goes.py"
        args:
          input_path: "./testinput/gdas.t00z.satwnd.tm00.bufr_d"
          mapping_path: "./bufr2ioda_satwnd_amv_goes_mapping.yaml"
          category: "goes-17"
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/script_backend/gdas.t00z.satwnd.abi_goes-17.tm00.nc"

- obs space:
    name: "satwind_goes-18"
    observed variables: [windSpeed, windDirection]
    derived variables: [windEastward, windNorthward]
    simulated variables: [windEastward, windNorthward]
    obsdatain:
      engine:
        type: script 
        script file: "bufr2ioda_satwnd_amv_goes.py"
        args:
          input_path: "./testinput/gdas.t00z.satwnd.tm00.bufr_d"
          mapping_path: "./bufr2ioda_satwnd_amv_goes_mapping.yaml"
          category: "goes-18"
    obsdataout:
      engine:
        type: H5File
        obsfile: "./testoutput/2021080100/script_backend/gdas.t00z.satwnd.abi_goes-18.tm00.nc"
