bufr:
  variables:
    # MetaData
    timestamp:
      datetime:
        year: "*/YEAR"
        month: "*/MNTH"
        day: "*/DAYS"
        hour: "*/HOUR"
        minute: "*/MINU"
        second: "*/SECO"

    latitude:
      query: "*/CLATH"

    longitude:
      query: "*/CLONH"

    amplitudeofstrike:
      query: "*/AMPLS"

    polarityofstroke:
      query: "*/PLRTS"

#    otherweatherphenomena:
#      query: "*/OWEP"

    numberofflashes:
      query: "*/NOFL"

    restrictionFlag:
      query: "*/RSRD"

    restrictionExpiration:
      query: "*/EXPRSRD"

encoder:
  globals:
    - name: "description"
      type: string
      value: "Total number of flashes (thunderstorm), retrieved from Vaisala lightning (NLDN short-range)"

    - name: "platformCommonName"
      type: string
      value: "Vaisala"

    - name: "source"
      type: string
      value: "U.S. National Weather Service, National Centers for Environmental Prediction (NCEP))"

    - name: "sourceFiles"
      type: string
      value: "NCEP BUFR Dump - NC007001"

    - name: "converter"
      type: string
      value: "bufr-query"

  variables:
    # MetaData
    - name: "MetaData/dateTime"
      source: variables/timestamp
      longName: "Datetime"
      units: "seconds since 1970-01-01T00:00:00Z"

    - name: "MetaData/latitude"
      source: variables/latitude
      longName: "Latitude"
      units: "degree_north"
      range: [-90, 90]

    - name: "MetaData/longitude"
      source: variables/longitude
      longName: "Longitude"
      units: "degree_east"

    - name: "MetaData/restrictionFlag"
      source: variables/restrictionFlag
      longName: "Restriction on Redistribution"

    - name: "MetaData/restrictionExpiration"
      source: variables/restrictionExpiration
      longName: "Expiration of Restriction on Redistribution"

    # ObsValue
    - name: "ObsValue/amplitudeofstrike"
      source: variables/amplitudeofstrike
      longName: "Amplitude of Stroke"
      units: "AMPS"

    - name: "ObsValue/polarityofstroke"
      source: variables/polarityofstroke
      longName: "Polarity of Stroke"

#    - name: "ObsValue/otherweatherphenomena"
#      source: variables/otherweatherphenomena
#      longName: "Other Weather Phenomena"

    - name: "ObsValue/numberofflashes"
      source: variables/numberofflashes
      longName: "Number of Flashes"
      units: "NUMERIC"
