#!/bin/bash -x

# Enable debugging mode
set -x

# Set unlimited stack size
ulimit -s unlimited
ulimit -a

export OOPS_TRACE=1
export OOPS_DEBUG=1

export PYTHONPATH="$PYTHONPATH:/work/noaa/da/eliu/HERCULES/JEDI-ioda/ioda-bundle/build/lib/python3.10"
export PYTHONPATH="$PYTHONPATH:/work/noaa/da/eliu/HERCULES/EMC-bufr-query/bufr-query/build/lib/python3.10/site-packages"
export PYTHONPATH="${PYTHONPATH}:/work/noaa/da/eliu/HERCULES/EMC-wxflow/wxflow/src"

# Date and processor count
cdate="2021080100"
nproc="$1"

# Extract year, month, day, and hour
y4="${cdate:0:4}"
m2="${cdate:4:2}"
d2="${cdate:6:2}"
h2="${cdate:8:2}"

work_dir="$PWD"
src_dir="/work/noaa/da/eliu/HERCULES/JEDI-ioda/ioda-bundle"
out_dir="${work_dir}/testoutput/$cdate/script_backend"
in_dir="${work_dir}/testinput/$cdate"

mkdir -p -m770 $out_dir

process_yaml="${work_dir}/bufr2ioda_script_backend_satwind.yaml"

# Run 
if [[ "$nproc" == "0" ]]; then
   echo Run time_IodaIO.x without MPI ...
   ${src_dir}/build/bin/time_IodaIO.x ${process_yaml}
else
   echo Run time_IodaIO.x with MPI ${nproc} ...
   srun -n $nproc  --mem 96G --time 00:30:00 ${src_dir}/build/bin/time_IodaIO.x ${process_yaml}
fi

